[package]
name = "il"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
il-graph.workspace = true
il-checker.workspace = true
il-frontend.workspace = true
il-hir.workspace = true
il-mir.workspace = true
il-interpreter.workspace = true
