"""Trusted P10 execution supervisor.

This module owns the small boundary between a reviewed command plan and the
raw observations used by the P10 bundle validator.  Callers select an output
directory only; they cannot supply commands, expected results, or a manifest.
Every command and its byte streams are retained before the next command is
started.  A failed run remains on disk and is never rewritten as a success.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import datetime as _datetime
import hashlib
import json
import os
from pathlib import Path
import shutil
import signal
import subprocess
import sys
import tempfile
import time
import uuid
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[2]
SCHEMA_VERSION = "1.0.0"
HASH_PREFIX = "sha256:"


class ProducerError(RuntimeError):
    """A run cannot be started, resumed, or published."""


@dataclass(frozen=True)
class CommandSpec:
    """One command from the reviewed, non-user-editable plan."""

    command_id: str
    argv: tuple[str, ...]
    timeout_seconds: int
    purpose: str
    output_paths: tuple[str, ...] = ()
    run_output_paths: tuple[str, ...] = ()


def digest_bytes(data: bytes) -> str:
    return HASH_PREFIX + hashlib.sha256(data).hexdigest()


def digest_file(path: Path) -> str:
    hasher = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            hasher.update(block)
    return HASH_PREFIX + hasher.hexdigest()


def canonical(value: Any) -> bytes:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")


def atomic_json(path: Path, value: Any) -> None:
    """Write a complete JSON snapshot and durably replace the old snapshot."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".pending", dir=path.parent)
    try:
        with os.fdopen(fd, "wb") as stream:
            stream.write(json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True).encode("utf-8"))
            stream.write(b"\n")
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
        try:
            directory_fd = os.open(path.parent, os.O_RDONLY)
            try:
                os.fsync(directory_fd)
            finally:
                os.close(directory_fd)
        except OSError:
            # Windows does not support opening a directory as a file.  The
            # file itself is still atomically replaced and fsynced above.
            pass
    finally:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass


def utc_now() -> str:
    return _datetime.datetime.now(_datetime.timezone.utc).isoformat().replace("+00:00", "Z")


def resolve_tool(name: str) -> str:
    path = Path(name)
    if path.is_absolute():
        return str(path)
    resolved = shutil.which(name)
    if not resolved:
        raise ProducerError(f"reviewed tool is unavailable: {name}")
    return str(Path(resolved).resolve())


def source_identity(root: Path) -> dict[str, Any]:
    """Read source identity without trusting a caller-provided commit/hash."""
    def git(*args: str) -> str:
        process = subprocess.run(
            [resolve_tool("git"), "-C", str(root), *args],
            cwd=root,
            env={"LC_ALL": "C", "LANG": "C", "PATH": os.environ.get("PATH", "")},
            capture_output=True,
            text=True,
            check=False,
        )
        if process.returncode != 0:
            raise ProducerError(f"git identity command failed: {' '.join(args)}: {process.stderr.strip()}")
        return process.stdout.strip()

    status = git("status", "--porcelain", "--untracked-files=all")
    commit = git("rev-parse", "HEAD")
    tree = git("rev-parse", "HEAD^{tree}")
    if not commit or not tree:
        raise ProducerError("source checkout has no committed HEAD")
    return {
        "repository": str(root.resolve()),
        "commit": commit,
        "tree": tree,
        "dirty": bool(status),
        "status": status,
    }


def _fixed_plan(output: Path) -> tuple[CommandSpec, ...]:
    """Return the only commands this supervisor may execute.

    The output path is generated by the supervisor and is the sole dynamic
    argument.  No command string, executable, or expected result is accepted
    from the CLI or an input manifest.
    """
    python = str(Path(sys.executable).resolve())
    ci = str((ROOT / "tools" / "ci" / "run.py").resolve())
    http = str((ROOT / "tests" / "http_blackbox" / "cli.py").resolve())
    compare = str((ROOT / "tools" / "p10" / "compare.py").resolve())
    reproduce = str((ROOT / "tools" / "p10" / "reproduce.py").resolve())
    return (
        CommandSpec("ci", (python, ci), 1800, "locked bootstrap and acceptance gates",
                    ("build/ci/result.json", "build/graph_cli_report.json", "build/semantic_cli_report.json",
                     "build/text_cli_report.json", "build/execution_cli_debug_report.json",
                     "build/native_cli_report.json", "build/runtime_cli_report.json",
                     "build/network_cli_report.json", "build/bytes_cli_report.json",
                     "build/http_cli_report.json", "build/ai_protocol_cli_report.json",
                     "build/interpreter_profile_parity_report.json",
                     "build/ci/*.log", "build/ci/*_report.json")),
        CommandSpec("http", (python, http, "--binary", str((ROOT / "target" / "release" / "il").resolve()),
                              "--report", str((output / "http" / "http_report.json").resolve())), 1200,
                    "locked external HTTP acceptance", (), ("http/http_report.json", "http/**")),
        CommandSpec("g4", (python, compare, "--output", str((output / "g4").resolve())), 900,
                    "locked 18-trial comparison", (), ("g4/comparison.json", "g4/**")),
        CommandSpec("reproducibility", (python, reproduce, "--output", str((output / "reproducibility").resolve())),
                    2400, "two independent locked compiler/runtime/application rebuilds", (),
                    ("reproducibility/reproduction.json", "reproducibility/**")),
    )


def _plan_identity(plan: tuple[CommandSpec, ...]) -> dict[str, Any]:
    """Hash the reviewed command plan and every script it invokes."""
    commands = []
    for spec in plan:
        script = Path(spec.argv[1]) if len(spec.argv) > 1 else Path(spec.argv[0])
        if not script.is_file():
            raise ProducerError(f"fixed plan script is missing: {script}")
        commands.append({
            "command_id": spec.command_id,
            "argv": list(spec.argv),
            "timeout_seconds": spec.timeout_seconds,
            "purpose": spec.purpose,
            "output_paths": list(spec.output_paths),
            "run_output_paths": list(spec.run_output_paths),
            "script": {"path": str(script), "sha256": digest_file(script)},
        })
    # Contract hashes are part of the plan identity. A run cannot silently
    # consume a changed HTTP/G4 contract while retaining an old receipt.
    contracts = []
    for path in (ROOT / "tools" / "p10" / "contract.json",
                 ROOT / "tools" / "p10" / "execution_contract.json",
                 ROOT / "spec" / "http.yaml"):
        if path.is_file():
            contracts.append({"path": str(path), "sha256": digest_file(path)})
    body = {"schema_version": SCHEMA_VERSION, "commands": commands, "contracts": contracts}
    body["sha256"] = digest_bytes(canonical(body))
    return body


def _permitted_environment(output: Path) -> dict[str, str]:
    """Construct the fixed environment recorded for every process."""
    keys = ("PATH", "HOME", "USERPROFILE", "SYSTEMROOT", "WINDIR", "PATHEXT", "CARGO_HOME", "RUSTUP_HOME", "LLVM_CONFIG_PATH")
    environment = {key: os.environ[key] for key in keys if os.environ.get(key) is not None}
    environment.update({"LC_ALL": "C", "LANG": "C", "PYTHONHASHSEED": "0", "SOURCE_DATE_EPOCH": "946684800"})
    # Keep command-local caches out of a user's home directory while retaining
    # only a generated path.  Do not copy precompiled outputs into this area.
    cache = output / "environment"
    cache.mkdir(parents=True, exist_ok=True)
    environment["HOME"] = str(cache)
    environment["USERPROFILE"] = str(cache)
    return dict(sorted(environment.items()))


def _blob(root: Path, data: bytes) -> dict[str, Any]:
    identity = digest_bytes(data)
    relative = Path("blobs") / identity.removeprefix(HASH_PREFIX)
    destination = root / relative
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists():
        if destination.read_bytes() != data:
            raise ProducerError(f"content-addressed blob collision: {identity}")
    else:
        temporary = destination.with_name(f".{destination.name}.pending")
        with temporary.open("wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, destination)
    return {"path": relative.as_posix(), "sha256": identity, "size_bytes": len(data)}


def _tool_identity(argv: tuple[str, ...]) -> dict[str, Any]:
    executable = Path(resolve_tool(argv[0]))
    if not executable.is_file():
        raise ProducerError(f"reviewed executable is not a file: {executable}")
    return {"path": str(executable), "sha256": digest_file(executable), "size_bytes": executable.stat().st_size}


def _argv_file_identities(argv: tuple[str, ...]) -> list[dict[str, Any]]:
    """Bind reviewed scripts and checked-in inputs present in an argv."""
    identities = []
    for argument in argv[1:]:
        candidate = Path(argument)
        if not candidate.is_absolute():
            candidate = (ROOT / candidate).resolve()
        if candidate.is_file() and candidate != Path(resolve_tool(argv[0])):
            identities.append({"path": str(candidate), "sha256": digest_file(candidate), "size_bytes": candidate.stat().st_size})
    return identities


def _signal_name(returncode: int | None) -> str | None:
    if returncode is None or returncode >= 0:
        return None
    try:
        return signal.Signals(-returncode).name
    except ValueError:
        return f"SIG{-returncode}"


def _observation(
    run_root: Path,
    spec: CommandSpec,
    environment: dict[str, str],
    source: dict[str, Any],
) -> dict[str, Any]:
    started_wall = utc_now()
    started_ns = time.monotonic_ns()
    argv = list(spec.argv)
    tool = _tool_identity(spec.argv)
    stdin = b""
    timed_out = False
    error: str | None = None
    stdout = b""
    stderr = b""
    returncode: int | None = None
    try:
        process = subprocess.Popen(
            argv,
            cwd=ROOT,
            env=environment,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        try:
            stdout, stderr = process.communicate(stdin, timeout=spec.timeout_seconds)
            returncode = process.returncode
        except subprocess.TimeoutExpired as timeout:
            timed_out = True
            process.kill()
            stdout, stderr = process.communicate()
            returncode = process.returncode
            error = f"timeout after {spec.timeout_seconds}s"
    except OSError as exc:
        error = f"process launch failed: {exc}"
    ended_ns = time.monotonic_ns()
    command = {
        "schema_version": SCHEMA_VERSION,
        "kind": "command_observation",
        "command_id": spec.command_id,
        "purpose": spec.purpose,
        "argv": argv,
        "argv_sha256": digest_bytes(canonical(argv)),
        "cwd": str(ROOT),
        "env": environment,
        "stdin": _blob(run_root, stdin),
        "started_at": started_wall,
        "started_monotonic_ns": started_ns,
        "ended_monotonic_ns": ended_ns,
        "elapsed_ns": ended_ns - started_ns,
        "exit_code": returncode if returncode is not None and returncode >= 0 else None,
        "termination_signal": _signal_name(returncode),
        "timed_out": timed_out,
        "stdout": _blob(run_root, stdout),
        "stderr": _blob(run_root, stderr),
        "tool": tool,
        "argv_files": _argv_file_identities(spec.argv),
        "source_commit": source["commit"],
        "status": "SUCCESS" if returncode == 0 and not error else "FAILED",
        "error": error,
    }
    return command


def _write_command(run_root: Path, command: dict[str, Any]) -> dict[str, Any]:
    command_id = command["command_id"]
    destination = run_root / "commands" / f"{command_id}.json"
    if destination.exists():
        raise ProducerError(f"command observation already exists: {command_id}")
    atomic_json(destination, command)
    return {"command_id": command_id, "path": destination.relative_to(run_root).as_posix(), "sha256": digest_file(destination)}


def _fixed_relative(value: str) -> Path:
    """Validate a reviewed relative path or glob before touching the filesystem."""
    if not isinstance(value, str) or not value or "\\" in value or ":" in value:
        raise ProducerError(f"fixed output path is not a relative POSIX path: {value!r}")
    relative = Path(value.replace("/", os.sep))
    if relative.is_absolute() or ".." in relative.parts:
        raise ProducerError(f"fixed output path is not relative: {value}")
    return relative


def _expand_paths(root: Path, paths: Iterable[str]) -> list[tuple[str, Path]]:
    """Expand only fixed relative paths/globs and return regular files in order."""
    expanded: list[tuple[str, Path]] = []
    seen: set[str] = set()
    for pattern in paths:
        relative = _fixed_relative(pattern)
        text = relative.as_posix()
        has_glob = any(marker in text for marker in ("*", "?", "["))
        candidates = sorted(root.glob(text)) if has_glob else [root / relative]
        for candidate in candidates:
            if not candidate.exists():
                continue
            if candidate.is_symlink():
                raise ProducerError(f"fixed output path is a symbolic link: {text}")
            if not candidate.is_file():
                continue
            relative_candidate = candidate.relative_to(root)
            cursor = root
            for part in relative_candidate.parts:
                cursor /= part
                if cursor.is_symlink():
                    raise ProducerError(f"fixed output path contains a symbolic link: {text}")
            resolved = candidate.resolve()
            try:
                resolved.relative_to(root.resolve())
            except ValueError as exc:
                raise ProducerError(f"fixed output path escapes its root: {text}") from exc
            actual = candidate.relative_to(root).as_posix()
            if actual not in seen:
                expanded.append((actual, candidate))
                seen.add(actual)
    return expanded


def _capture_checkout_paths(run_root: Path, paths: Iterable[str]) -> list[dict[str, Any]]:
    """Copy reviewed checkout outputs into the run and bind their hashes."""
    captured: list[dict[str, Any]] = []
    for pattern in tuple(paths):
        normalized = _fixed_relative(pattern).as_posix()
        matches = _expand_paths(ROOT, (normalized,))
        if not matches:
            captured.append({"path": normalized, "present": False})
            continue
        for relative, path in matches:
            data = path.read_bytes()
            # Preserve the reviewed output at its checkout-relative location so
            # a later assembler can consume reports without reaching back into
            # the mutable checkout. The content-addressed blob remains the
            # identity used by command observations.
            relative_path = Path(relative.replace("/", os.sep))
            retained = run_root / relative_path
            retained.parent.mkdir(parents=True, exist_ok=True)
            if retained.exists() and retained.read_bytes() != data:
                raise ProducerError(f"captured output collision: {relative}")
            if not retained.exists():
                pending = retained.with_name(f".{retained.name}.pending")
                with pending.open("wb") as stream:
                    stream.write(data)
                    stream.flush()
                    os.fsync(stream.fileno())
                os.replace(pending, retained)
            captured.append({
                "path": relative,
                "present": True,
                "sha256": digest_bytes(data),
                "size_bytes": len(data),
                "bytes": _blob(run_root, data),
            })
    return captured


def _capture_run_paths(run_root: Path, paths: Iterable[str]) -> list[dict[str, Any]]:
    """Bind files emitted below the command's supervisor-owned run directory."""
    captured: list[dict[str, Any]] = []
    seen: set[str] = set()
    for pattern in paths:
        normalized = _fixed_relative(pattern).as_posix()
        matches = _expand_paths(run_root, (normalized,))
        if not matches:
            captured.append({"path": normalized, "present": False})
            continue
        for relative, path in matches:
            if relative in seen:
                continue
            seen.add(relative)
            data = path.read_bytes()
            captured.append({
                "path": relative,
                "present": True,
                "sha256": digest_bytes(data),
                "size_bytes": len(data),
            })
    return captured


def _capture_paths(run_root: Path, paths: Iterable[str]) -> list[dict[str, Any]]:
    """Capture reviewed checkout outputs using the canonical checkout path."""
    return _capture_checkout_paths(run_root, paths)


def _toolchain_identity() -> dict[str, Any]:
    lock = ROOT / "toolchain.lock"
    if not lock.is_file():
        raise ProducerError("toolchain.lock is missing")
    tools: dict[str, Any] = {"rustc": None, "llvm_config": None}
    for key, executable, args in (("rustc", "rustc", ("--version",)), ("llvm_config", "llvm-config-14", ("--version",))):
        path = Path(resolve_tool(executable))
        probe = subprocess.run(
            [str(path), *args],
            cwd=ROOT,
            env={"LC_ALL": "C", "LANG": "C", "PATH": os.environ.get("PATH", "")},
            capture_output=True,
            check=False,
        )
        if probe.returncode != 0:
            detail = probe.stderr.decode(errors="replace").strip()
            raise ProducerError(
                f"reviewed tool probe failed: {executable} (exit {probe.returncode})"
                + (f": {detail}" if detail else "")
            )
        version = probe.stdout.decode(errors="replace").strip()
        if not version:
            raise ProducerError(f"reviewed tool probe returned no version: {executable}")
        tools[key] = {
            "path": str(path),
            "sha256": digest_file(path),
            "version": version,
            "probe_exit_code": probe.returncode,
        }
    return {"lock": {"path": str(lock.relative_to(ROOT).as_posix()), "sha256": digest_file(lock)}, "tools": tools}


def _execution_context() -> dict[str, Any]:
    """Record the host restrictions that affect whether evidence is portable."""
    ci = {
        key: os.environ[key]
        for key in ("CI", "GITHUB_ACTIONS", "GITHUB_RUN_ID", "GITHUB_RUN_ATTEMPT",
                    "GITHUB_JOB", "GITHUB_WORKFLOW", "GITHUB_SHA", "GITHUB_REF")
        if os.environ.get(key) is not None
    }
    return {
        "platform": sys.platform,
        "system": os.name,
        "machine": __import__("platform").machine(),
        "python": sys.version,
        "ci": ci,
        "container_image": os.environ.get("IL_TOOLCHAIN_IMAGE"),
        "network": "disabled_by_command_plan" if os.environ.get("CI") else "host_policy_recorded",
    }


def run_plan(output: str | Path, *, root: Path = ROOT) -> dict[str, Any]:
    """Execute the reviewed plan and retain a complete or failed run."""
    global ROOT
    if root.resolve() != ROOT.resolve():
        # Tests and hermetic callers may provide a checkout, but command paths
        # remain derived from that checkout rather than from caller commands.
        old_root = ROOT
        ROOT = root.resolve()
    else:
        old_root = None
    try:
        destination = Path(output).resolve()
        if destination.exists():
            raise ProducerError(f"refusing to overwrite existing evidence: {destination}")
        destination.mkdir(parents=True)
        source = source_identity(ROOT)
        if source["dirty"]:
            raise ProducerError("P10 trusted execution requires a clean committed checkout")
        run_id = "p10_" + uuid.uuid4().hex
        state: dict[str, Any] = {
            "schema_version": SCHEMA_VERSION,
            "kind": "p10_trusted_run",
            "run_id": run_id,
            "status": "RUNNING",
            "started_at": utc_now(),
            "source": source,
            "toolchain": None,
            "execution_context": _execution_context(),
            "supervisor": {"path": str(Path(__file__).resolve()), "sha256": digest_file(Path(__file__))},
            "plan": None,
            "commands": [],
            "failure": None,
        }
        atomic_json(destination / "journal.json", state)
        try:
            toolchain = _toolchain_identity()
            plan = _fixed_plan(destination)
            plan_identity = _plan_identity(plan)
            state["toolchain"] = toolchain
            state["plan"] = plan_identity
            atomic_json(destination / "journal.json", state)
            environment = _permitted_environment(destination)
            for spec in plan:
                observation = _observation(destination, spec, environment, source)
                observation["outputs"] = (
                    _capture_checkout_paths(destination, spec.output_paths)
                    + _capture_run_paths(destination, spec.run_output_paths)
                )
                reference = _write_command(destination, observation)
                state["commands"].append(reference)
                state["active_command"] = spec.command_id
                atomic_json(destination / "journal.json", state)
                if observation["status"] != "SUCCESS":
                    state["status"] = "FAILED"
                    state["failure"] = {"command_id": spec.command_id, "error": observation["error"], "exit_code": observation["exit_code"], "termination_signal": observation["termination_signal"]}
                    state["finished_at"] = utc_now()
                    atomic_json(destination / "journal.json", state)
                    return state
            state.pop("active_command", None)
            state["status"] = "COMPLETE"
            state["finished_at"] = utc_now()
            atomic_json(destination / "journal.json", state)
            return state
        except BaseException as exc:
            state["status"] = "FAILED"
            state["failure"] = {"error": f"supervisor failure: {exc.__class__.__name__}: {exc}"}
            state["finished_at"] = utc_now()
            atomic_json(destination / "journal.json", state)
            raise
    finally:
        if old_root is not None:
            ROOT = old_root


def publish_release(run_root: str | Path, release_root: str | Path) -> dict[str, Any]:
    """Publish a content-addressed trusted-run receipt exactly once.

    This writes only a supervisor manifest.  The normal P10 bundle assembler
    still has to validate all language predicates before a release is eligible.
    """
    run = Path(run_root).resolve()
    destination = Path(release_root).resolve()
    journal_path = run / "journal.json"
    if not journal_path.is_file():
        raise ProducerError("trusted run journal is missing")
    journal = json.loads(journal_path.read_text(encoding="utf-8"))
    if journal.get("status") != "COMPLETE":
        raise ProducerError("only a complete trusted run may be published")
    commands = journal.get("commands")
    if not isinstance(commands, list) or not commands:
        raise ProducerError("trusted run has no command observations")
    for reference in commands:
        record = json.loads((run / reference["path"]).read_text(encoding="utf-8"))
        if record.get("status") != "SUCCESS":
            raise ProducerError("trusted run contains a failed command")
    manifest = {
        "schema_version": SCHEMA_VERSION,
        "kind": "p10_trusted_run_publication",
        "run_id": journal["run_id"],
        "source": journal["source"],
        "toolchain": journal["toolchain"],
        "journal": {"path": str(journal_path), "sha256": digest_file(journal_path)},
        "commands": journal["commands"],
        "published_at": utc_now(),
    }
    if destination.exists():
        existing = destination / "trusted_run.json"
        if not existing.is_file():
            raise ProducerError("refusing to overwrite an existing release")
        try:
            prior = json.loads(existing.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            raise ProducerError("existing release is not valid JSON") from exc
        immutable_fields = ("schema_version", "kind", "run_id", "source", "toolchain", "journal", "commands")
        if all(prior.get(field) == manifest[field] for field in immutable_fields):
            return prior
        raise ProducerError("refusing to overwrite an existing release")
    destination.mkdir(parents=True)
    atomic_json(destination / "trusted_run.json", manifest)
    return manifest


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, allow_abbrev=False)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args(list(argv) if argv is not None else None)
    try:
        result = run_plan(args.output)
    except ProducerError as exc:
        print(json.dumps({"ok": False, "status": "BLOCKED", "error": str(exc)}, ensure_ascii=False))
        return 2
    print(json.dumps({"ok": result["status"] == "COMPLETE", "status": result["status"], "run_id": result["run_id"]}, ensure_ascii=False))
    return 0 if result["status"] == "COMPLETE" else 1


if __name__ == "__main__":
    raise SystemExit(main())
